"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.host import Host
globals()['Host'] = Host
from qarax.model.host_list_response import HostListResponse


class TestHostListResponse(unittest.TestCase):
    """HostListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostListResponse(self):
        """Test HostListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HostListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
