"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.storage import Storage
globals()['Storage'] = Storage
from qarax.model.storage_list_response import StorageListResponse


class TestStorageListResponse(unittest.TestCase):
    """StorageListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageListResponse(self):
        """Test StorageListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
