"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import qarax
from qarax.api.vms_api import VMsApi  # noqa: E501


class TestVMsApi(unittest.TestCase):
    """VMsApi unit test stubs"""

    def setUp(self):
        self.api = VMsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_vm(self):
        """Test case for add_vm

        Create new VM  # noqa: E501
        """
        pass

    def test_get_vm(self):
        """Test case for get_vm

        Get VM by ID  # noqa: E501
        """
        pass

    def test_list_vms(self):
        """Test case for list_vms

        Get VM list  # noqa: E501
        """
        pass

    def test_start_vm(self):
        """Test case for start_vm

        Start a VM  # noqa: E501
        """
        pass

    def test_stop_vm(self):
        """Test case for stop_vm

        Stop a VM  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
