"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.creation_response import CreationResponse


class TestCreationResponse(unittest.TestCase):
    """CreationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreationResponse(self):
        """Test CreationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
