"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.install_response import InstallResponse


class TestInstallResponse(unittest.TestCase):
    """InstallResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstallResponse(self):
        """Test InstallResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstallResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
