"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import qarax
from qarax.api.storage_api import StorageApi  # noqa: E501


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_storage(self):
        """Test case for add_storage

        Create new storage  # noqa: E501
        """
        pass

    def test_get_storage(self):
        """Test case for get_storage

        Get storage by ID  # noqa: E501
        """
        pass

    def test_list_storage(self):
        """Test case for list_storage

        Get storage list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
