"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.storage_config import StorageConfig


class TestStorageConfig(unittest.TestCase):
    """StorageConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageConfig(self):
        """Test StorageConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
