"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qarax
from qarax.model.host import Host
globals()['Host'] = Host
from qarax.model.host_list import HostList


class TestHostList(unittest.TestCase):
    """HostList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostList(self):
        """Test HostList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HostList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
