# flake8: noqa

"""
    qarax API

    The API for qarax manager  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from qarax.api_client import ApiClient

# import Configuration
from qarax.configuration import Configuration

# import exceptions
from qarax.exceptions import OpenApiException
from qarax.exceptions import ApiAttributeError
from qarax.exceptions import ApiTypeError
from qarax.exceptions import ApiValueError
from qarax.exceptions import ApiKeyError
from qarax.exceptions import ApiException
